name: build

on:
  push:
    branches: [ main ]
    paths:
      - 'JAMS2Dacier/**'
      - '.github/workflows/build.yaml'

  pull_request:
    branches: [ main ]
    paths:
      - 'JAMS2Dacier/**'
      - '.github/workflows/build.yaml'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: write
    defaults:
      run:
        shell: bash

    steps:

    #
    #  Prepare the environment
    #
    - name: Checkout Repository
      uses: actions/checkout@v6

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.0.x

    #
    #  Build
    #
    - name: Restore Workloads
      shell: bash
      run: dotnet workload restore

    - name: Restore dependencies
      shell: bash
      run: dotnet restore

    - name: Build
      shell: bash
      run: dotnet build --no-restore --configuration Release

    #
    #  Print Folder Tree
    #  Usually commented out but useful for debugging
    #
    - name: Print Folder Tree
      uses: jaywcjlove/github-action-folder-tree@main
      with:
        path: ./JAMS2Dacier
        depth: 8

    #
    #  Package
    #
    - name: Get Version
      shell: pwsh
      run: |
        $versionInfo = (Get-Item JAMS2Dacier\bin\Release\net10.0\JAMS2Dacier.dll).VersionInfo
        $formattedVersion = "{0}.{1}.{2}" -f $versionInfo.ProductMajorPart, $versionInfo.ProductMinorPart, $versionInfo.ProductBuildPart
        write-host "Version is: $formattedVersion"
        echo "version=$formattedVersion" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append

    #
    #  Push packages to NuGet.org
    #
    - name: NuGet login (OIDC → temp API key)
      uses: NuGet/login@v1
      id: login
      with:
        user: johnvotterodacier
    
    - name: NuGet push JAMS2Dacier
      shell: bash
      run: dotnet nuget push JAMS2Dacier/bin/Release/Dacier.JAMS2Dacier.${{ env.version }}.nupkg --api-key ${{steps.login.outputs.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate

